### ISSUE TITLE
BS environmental/habitat covariates

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [alaska-groundfish-efh/product-requests#8]
Transferred from [https://github.com/afsc-gap-products/data-requests/issues/105](https://github.com/afsc-gap-products/data-requests/issues/105)

**Data product requested (EFH, abundance, etc.)**: 
all environmental and habitat covariates compiled for EFH SDM models. for layers that vary year-to-year, please include 2021-2024

**Species**: NA

**Lifestage(s)**: NA

**Region(s)** (GOA, AI, Bering Sea):
BS (Bering Sea) - 2021 to 2024

**Format**: 

- [ x] Raster
- [ ] Shapefile

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.):
Kimberly Ledger, Research Biologist, AFSC Genetics Program, @kjledger-NOAA

**What will this EFH product be used for?**:

**Comment by MallarieYeager-NOAA** [comment]
Hi Kim,

Unfortunately, the data product you've requested doesn't exist, yet. EFH rasters are updated for the EFH 5-year reviews and are vetted/approved through the north pacific fishery management council. There have been no updates to the rasters since the last cycle, so the most recent available version of the data product includes covariates through 2019.

Table 3 of [Laman et al., (2022), pages 35-36](https://repository.library.noaa.gov/view/noaa/48659) describes the rasters that were used for the most recent 5-year update, along with data sources and interpolation methods. The rasters for dynamic variables (i.e., time-varying environmental variables) were constructed using interpolated data from 1982-2019.  

If you would like any or all annual-varying covariate rasters up to 2019, we can get you those data. If so, please specify the year range you need. 

Thanks

**Comment by kjledger-NOAA** [comment]
Hi Mallarie,

Thanks for the reply. That's a bummer but it makes sense.  Okay, so looking
at Table 3 of Lamen et al., 2022, it is the temperature and current
variables that were constructed using the interpolated data over time. And
all the others are less dynamic (at least within the time scale of the last
few decades), correct?  Would it be possible to get the EFH raster for the
most recent 50-year review? and then I can replace the dynamic ones with
data from other sources. I'm aware of Bering Sea temperature data being
available from the afsc-gap-products.

Best,
Kim

**Comment by MallarieYeager-NOAA** [comment]
Hi Kim, 

Yes, the temporally varying covariates are: (1) bottom temp (spatially interpolated from bottom trawl survey measurements), (2) bottom current (from 10k BS ROMS) and (3) bottom current variability (from 10k BS ROMS).

Okay, just so I'm understanding your request. You would like the full suite of BS covariate rasters from the last 5-yr EFH review, and you will update the temporally varying ones through other data sources? 

Thanks
Mallarie

**Comment by kjledger-NOAA** [comment]
Yes, that is correct. Thank you!

**Comment by MallarieYeager-NOAA** [comment]
Hi Kim, 

[Here ](https://drive.google.com/drive/folders/18TULctO1d8MwBrp_-vzMdEKss_H-R1Kr?usp=sharing)is the drive folder with the covariates from the most recent review. 

If you are publishing or presenting these data make sure to cite both these papers: [Laman et al., 2022](https://repository.library.noaa.gov/view/noaa/48659) and[ Harris et al., 2023](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.14559).

Lastly, could you provide a reason for needing this data? This doesn't need to be super developed explanation, its just helpful for our basic EFH data-use tracking needs :) Thank you!

**Comment by kjledger-NOAA** [comment]
Thank you! And yes, I will be sure to include those citations on any work
that comes from this.

The data will be used with environmental DNA derived presence/absence and
relative abundance data for species distribution modeling.

Best,
Kim

**Comment by MallarieYeager-NOAA** [comment]
Thank you Kim! :)
